/*
 * WorkloadItem: each item generated by workload generator.
 * 
 * By Siyuan Sheng (2023.04.18).
 */

#ifndef WORKLOAD_ITEM_H
#define WORKLOAD_ITEM_H

#include <string>

#include "common/dynamic_array.h"
#include "common/key.h"
#include "common/value.h"

namespace covered
{
    enum WorkloadItemType
    {
        kWorkloadItemGet = 1,
        kWorkloadItemPut,
        kWorkloadItemDel
    };

    class WorkloadItem
    {
    public:
        static std::string workloadItemTypeToString(const WorkloadItemType& item_type);

        WorkloadItem(const Key& key, const Value& value, const WorkloadItemType& item_type);
        ~WorkloadItem();

        Key getKey();
        Value getValue();
        WorkloadItemType getItemType();
    private:
        static const std::string kClassName;

        Key key_;
        Value value_;
        WorkloadItemType item_type_;
    };
}

#endif