# smhasher module

SMHASHER_DIRPATH := lib/smhasher

SMHASHER_SRCFILES = $(wildcard $(SMHASHER_DIRPATH)/*.cpp)
SMHASHER_OBJECTS += $(SMHASHER_SRCFILES:.c=.o)
SMHASHER_SHARED_OBJECTS += $(SMHASHER_SRCFILES:.c=.shared.o)
DEPS += $(SMHASHER_SRCFILES:.c=.d)
CLEANS += $(SMHASHER_OBJECTS) $(SMHASHER_SHARED_OBJECTS)

SMHASHER_INCDIR := -I$(SMHASHER_DIRPATH)/src
INCDIR += $(SMHASHER_INCDIR)