# smhasher module

SMHASHER_DIRPATH := lib/smhasher

SMHASHER_SRCFILES = $(filter-out $(SMHASHER_DIRPATH)/src/main.cpp, $(wildcard $(SMHASHER_DIRPATH)/src/*.cpp))
SMHASHER_OBJECTS += $(SMHASHER_SRCFILES:.cpp=.opp)
SMHASHER_SHARED_OBJECTS += $(SMHASHER_SRCFILES:.cpp=.shared.opp)
DEPS += $(SMHASHER_SRCFILES:.cpp=.dpp)
CLEANS += $(SMHASHER_OBJECTS) $(SMHASHER_SHARED_OBJECTS)
LINK_OBJECTS += $(SMHASHER_OBJECTS)

SMHASHER_INCDIR := -I$(SMHASHER_DIRPATH)/src
INCDIR += $(SMHASHER_INCDIR)