# tommyds module

TOMMYDS_DIRPATH := lib/tommyds

TOMMYDS_INRDIR := -I$(TOMMYDS_DIRPATH)/tommyds
INCDIR += $(TOMMYDS_INRDIR)

TOMMYDS_SRCFILES = $(wildcard $(TOMMYDS_DIRPATH)/tommyds/tommyds.c)
TOMMYDS_OBJECTS += $(TOMMYDS_SRCFILES:.c=.o)
TOMMYDS_SHARED_OBJECTS += $(TOMMYDS_SRCFILES:.c=.shared.o)
DEPS += $(TOMMYDS_SRCFILES:.c=.d)
CLEANS += $(TOMMYDS_OBJECTS) $(TOMMYDS_SHARED_OBJECTS)
LINK_OBJECTS += $(TOMMYDS_OBJECTS)