# tommyds module

TOMMYDS_DIRPATH := lib/tommyds

TOMMYDS_INRDIR := -I$(TOMMYDS_DIRPATH)/tommyds
INCDIR += $(TOMMYDS_INRDIR)

TOMMYDS_LDDIR := -L$(TOMMYDS_DIRPATH)
LDDIR += $(TOMMYDS_LDDIR)

TOMMYDS_LDLIBS := -l:libtommy.a
LDLIBS += $(TOMMYDS_LDLIBS)