#!/bin/bash
#
# This script will only run on a computer using the IP
# address: 137.189.88.229.
#
# This auto-generated script was downloaded from http://iotta.snia.org.
# It will download the 144 subtraces of Tencent Photo Cache
#
echo "Downloading the 144 subtraces of Tencent Photo Cache" 1>&2
cookies=$(mktemp)
cat >> $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

.iotta.snia.org	TRUE	/	FALSE	0	infodigest	44dd7584426512a2dc6e032de6a7c9a70c94a426
.iotta.snia.org	TRUE	/	FALSE	0	legal	true
.iotta.snia.org	TRUE	/	FALSE	0	id	1189747
.iotta.snia.org	TRUE	/	FALSE	0	user_ip	137.189.88.229
EOF

if which wget >/dev/null 2>&1; then
  useWGET=true
elif which curl >/dev/null 2>&1; then
  useCURL=true
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
  exit 1
fi

checkForError() {
  delete=false
  if $useWGET && (( $1 == 2 || $1 == 3 || $1 == 5 || $1 == 7 || $1 == 8 ))
  then
    delete=true
  elif $useWGET && [ ! -s "$2" ]
  then
    delete=true
  elif $useCURL && (( $1 == 22 || $1 == 36 ))
  then
    delete=true
  fi
}

downloadFile() {
  file=$1
  id=$2
  url="http://server4.iotta.snia.org/traces/parallel/$id/download?type=file&sType="
  if $useWGET; then
    wget -q --content-on-error --load-cookies=$cookies -O "$file" -c "$url""wget"
    error=$?
  elif $useCURL; then
    curl -s -f -b $cookies -o "$file" -C - -L "$url""curl"
    error=$?
    if [ $error -eq 22 ]; then
      curl -s -b $cookies -o "$file" -C - -L "$url""curl"
    fi
  fi

  if [ $error -eq 0 ]; then
    echo "Finished Downloading $file"
  else
    checkForError $error "$file"
    downloadLink="http://iotta.snia.org/downloaderinfos/new?trace_id=27476&type=subtracesViaScript&sType=&came_from=iotta.snia.org"
    if $delete; then
      echo "There was an error downloading the file ($file)"
      if grep "internal iotta error: ip mismatch" "$file" > /dev/null; then
        echo "This script will only run on a computer with the IP address 137.189.88.229."
        grep "Your current IP address is" "$file"
        echo "Please use the following link to fill out the download license form with your current IP address and run the new script:"
        echo "$downloadLink"
      elif grep "internal iotta error: invalid cookie" "$file" > /dev/null; then
        echo "Invalid cookie, please use the following link to fill out the form and try again:"
        echo "$downloadLink"
      fi
      rm -f "$file"
    else
      echo "$file was only partially downloaded."
    fi
    echo "Stopping..."
    exit 1
  fi
}

# Dataset 1
downloadFile "cloud_photos-001.tbz2" 27482
downloadFile "cloud_photos-002.tbz2" 27485
downloadFile "cloud_photos-003.tbz2" 27488
downloadFile "cloud_photos-004.tbz2" 27491
downloadFile "cloud_photos-005.tbz2" 27494
downloadFile "cloud_photos-006.tbz2" 27497
downloadFile "cloud_photos-007.tbz2" 27500
downloadFile "cloud_photos-008.tbz2" 27503
downloadFile "cloud_photos-009.tbz2" 27506
downloadFile "cloud_photos-010.tbz2" 27509
downloadFile "cloud_photos-011.tbz2" 27512
downloadFile "cloud_photos-012.tbz2" 27515
downloadFile "cloud_photos-013.tbz2" 27518
downloadFile "cloud_photos-014.tbz2" 27521
downloadFile "cloud_photos-015.tbz2" 27524
downloadFile "cloud_photos-016.tbz2" 27527
downloadFile "cloud_photos-017.tbz2" 27530
downloadFile "cloud_photos-018.tbz2" 27533
downloadFile "cloud_photos-019.tbz2" 27536
downloadFile "cloud_photos-020.tbz2" 27539
downloadFile "cloud_photos-021.tbz2" 27542
downloadFile "cloud_photos-022.tbz2" 27545
downloadFile "cloud_photos-023.tbz2" 27548
downloadFile "cloud_photos-024.tbz2" 27551
downloadFile "cloud_photos-025.tbz2" 27554
downloadFile "cloud_photos-026.tbz2" 27557
downloadFile "cloud_photos-027.tbz2" 27560
downloadFile "cloud_photos-028.tbz2" 27563
downloadFile "cloud_photos-029.tbz2" 27566
downloadFile "cloud_photos-030.tbz2" 27569
downloadFile "cloud_photos-031.tbz2" 27572
downloadFile "cloud_photos-032.tbz2" 27575
downloadFile "cloud_photos-033.tbz2" 27578
downloadFile "cloud_photos-034.tbz2" 27581
downloadFile "cloud_photos-035.tbz2" 27584
downloadFile "cloud_photos-036.tbz2" 27587
downloadFile "cloud_photos-037.tbz2" 27590
downloadFile "cloud_photos-038.tbz2" 27593
downloadFile "cloud_photos-039.tbz2" 27596
downloadFile "cloud_photos-040.tbz2" 27599
downloadFile "cloud_photos-041.tbz2" 27602
downloadFile "cloud_photos-042.tbz2" 27605
downloadFile "cloud_photos-043.tbz2" 27608
downloadFile "cloud_photos-044.tbz2" 27611
downloadFile "cloud_photos-045.tbz2" 27614
downloadFile "cloud_photos-046.tbz2" 27617
downloadFile "cloud_photos-047.tbz2" 27620
downloadFile "cloud_photos-048.tbz2" 27623
downloadFile "cloud_photos-049.tbz2" 27626
downloadFile "cloud_photos-050.tbz2" 27629
downloadFile "cloud_photos-051.tbz2" 27632
downloadFile "cloud_photos-052.tbz2" 27635
downloadFile "cloud_photos-053.tbz2" 27638
downloadFile "cloud_photos-054.tbz2" 27641
downloadFile "cloud_photos-055.tbz2" 27644
downloadFile "cloud_photos-056.tbz2" 27647
downloadFile "cloud_photos-057.tbz2" 27650
downloadFile "cloud_photos-058.tbz2" 27653
downloadFile "cloud_photos-059.tbz2" 27656
downloadFile "cloud_photos-060.tbz2" 27659
downloadFile "cloud_photos-061.tbz2" 27662
downloadFile "cloud_photos-062.tbz2" 27665
downloadFile "cloud_photos-063.tbz2" 27668
downloadFile "cloud_photos-064.tbz2" 27671
downloadFile "cloud_photos-065.tbz2" 27674
downloadFile "cloud_photos-066.tbz2" 27677
downloadFile "cloud_photos-067.tbz2" 27680
downloadFile "cloud_photos-068.tbz2" 27683
downloadFile "cloud_photos-069.tbz2" 27686
downloadFile "cloud_photos-070.tbz2" 27689
downloadFile "cloud_photos-071.tbz2" 27692
downloadFile "cloud_photos-072.tbz2" 27695
downloadFile "cloud_photos-073.tbz2" 27698
downloadFile "cloud_photos-074.tbz2" 27701

# Dataset 2
downloadFile "cloud_photos-075.tbz2" 27707
downloadFile "cloud_photos-076.tbz2" 27710
downloadFile "cloud_photos-077.tbz2" 27713
downloadFile "cloud_photos-078.tbz2" 27716
downloadFile "cloud_photos-079.tbz2" 27719
downloadFile "cloud_photos-080.tbz2" 27722
downloadFile "cloud_photos-081.tbz2" 27725
downloadFile "cloud_photos-082.tbz2" 27728
downloadFile "cloud_photos-083.tbz2" 27731
downloadFile "cloud_photos-084.tbz2" 27734
downloadFile "cloud_photos-085.tbz2" 27737
downloadFile "cloud_photos-086.tbz2" 27740
downloadFile "cloud_photos-087.tbz2" 27743
downloadFile "cloud_photos-088.tbz2" 27746
downloadFile "cloud_photos-089.tbz2" 27749
downloadFile "cloud_photos-090.tbz2" 27752
downloadFile "cloud_photos-091.tbz2" 27755
downloadFile "cloud_photos-092.tbz2" 27758
downloadFile "cloud_photos-093.tbz2" 27761
downloadFile "cloud_photos-094.tbz2" 27764
downloadFile "cloud_photos-095.tbz2" 27767
downloadFile "cloud_photos-096.tbz2" 27770
downloadFile "cloud_photos-097.tbz2" 27773
downloadFile "cloud_photos-098.tbz2" 27776
downloadFile "cloud_photos-099.tbz2" 27779
downloadFile "cloud_photos-100.tbz2" 27782
downloadFile "cloud_photos-101.tbz2" 27785
downloadFile "cloud_photos-102.tbz2" 27788
downloadFile "cloud_photos-103.tbz2" 27791
downloadFile "cloud_photos-104.tbz2" 27794
downloadFile "cloud_photos-105.tbz2" 27797
downloadFile "cloud_photos-106.tbz2" 27800
downloadFile "cloud_photos-107.tbz2" 27803
downloadFile "cloud_photos-108.tbz2" 27806
downloadFile "cloud_photos-109.tbz2" 27809
downloadFile "cloud_photos-110.tbz2" 27812
downloadFile "cloud_photos-111.tbz2" 27815
downloadFile "cloud_photos-112.tbz2" 27818
downloadFile "cloud_photos-113.tbz2" 27821
downloadFile "cloud_photos-114.tbz2" 27824
downloadFile "cloud_photos-115.tbz2" 27827
downloadFile "cloud_photos-116.tbz2" 27830
downloadFile "cloud_photos-117.tbz2" 27833
downloadFile "cloud_photos-118.tbz2" 27836
downloadFile "cloud_photos-119.tbz2" 27839
downloadFile "cloud_photos-120.tbz2" 27842
downloadFile "cloud_photos-121.tbz2" 27845
downloadFile "cloud_photos-122.tbz2" 27848
downloadFile "cloud_photos-123.tbz2" 27851
downloadFile "cloud_photos-124.tbz2" 27854
downloadFile "cloud_photos-125.tbz2" 27857
downloadFile "cloud_photos-126.tbz2" 27860
downloadFile "cloud_photos-127.tbz2" 27863
downloadFile "cloud_photos-128.tbz2" 27866
downloadFile "cloud_photos-129.tbz2" 27869
downloadFile "cloud_photos-130.tbz2" 27872
downloadFile "cloud_photos-131.tbz2" 27875
downloadFile "cloud_photos-132.tbz2" 27878
downloadFile "cloud_photos-133.tbz2" 27881
downloadFile "cloud_photos-134.tbz2" 27884
downloadFile "cloud_photos-135.tbz2" 27887
downloadFile "cloud_photos-136.tbz2" 27890
downloadFile "cloud_photos-137.tbz2" 27893
downloadFile "cloud_photos-138.tbz2" 27896
downloadFile "cloud_photos-139.tbz2" 27899
downloadFile "cloud_photos-140.tbz2" 27902
downloadFile "cloud_photos-141.tbz2" 27905
downloadFile "cloud_photos-142.tbz2" 27908
downloadFile "cloud_photos-143.tbz2" 27911
downloadFile "cloud_photos-144.tbz2" 27914

echo "Finished All Downloads"
rm -f $cookies
