COVERED_DIRPATH = src
COVERED_INCDIR = -I$(COVERED_DIRPATH)
INCDIR += $(COVERED_INCDIR)

# benchmark module
BENCHMARK_SRCFILES := $(wildcard $(COVERED_DIRPATH)/benchmark/*.c)
BENCHMARK_OBJECTS += $(BENCHMARK_SRCFILES:.c=.o)
BENCHMARK_SHARED_OBJECTS += $(BENCHMARK_SRCFILES:.c=.shared.o)
DEPS += $(BENCHMARK_SRCFILES:.c=.d)
CLEANS += $(BENCHMARK_OBJECTS) $(BENCHMARK_SHARED_OBJECTS)

# cache module
CACHE_SRCFILES := $(wildcard $(COVERED_DIRPATH)/cache/*.c)
CACHE_OBJECTS += $(CACHE_SRCFILES:.c=.o)
CACHE_SHARED_OBJECTS += $(CACHE_SRCFILES:.c=.shared.o)
DEPS += $(CACHE_SRCFILES:.c=.d)
CLEANS += $(CACHE_OBJECTS) $(CACHE_SHARED_OBJECTS)

# cloud module
CLOUD_SRCFILES := $(wildcard $(COVERED_DIRPATH)/cloud/*.c)
CLOUD_OBJECTS += $(CLOUD_SRCFILES:.c=.o)
CLOUD_SHARED_OBJECTS += $(CLOUD_SRCFILES:.c=.shared.o)
DEPS += $(CLOUD_SRCFILES:.c=.d)
CLEANS += $(CLOUD_OBJECTS) $(CLOUD_SHARED_OBJECTS)

# common module
COMMON_SRCFILES := $(wildcard $(COVERED_DIRPATH)/common/*.c)
COMMON_OBJECTS += $(COMMON_SRCFILES:.c=.o)
COMMON_SHARED_OBJECTS += $(COMMON_SRCFILES:.c=.shared.o)
DEPS += $(COMMON_SRCFILES:.c=.d)
CLEANS += $(COMMON_OBJECTS) $(COMMON_SHARED_OBJECTS)

# edge module
EDGE_SRCFILES := $(wildcard $(COVERED_DIRPATH)/edge/*.c)
EDGE_OBJECTS += $(EDGE_SRCFILES:.c=.o)
EDGE_SHARED_OBJECTS += $(EDGE_SRCFILES:.c=.shared.o)
DEPS += $(EDGE_SRCFILES:.c=.d)
CLEANS += $(EDGE_OBJECTS) $(EDGE_SHARED_OBJECTS)

# message module
MESSAGE_SRCFILES := $(wildcard $(COVERED_DIRPATH)/message/*.c)
MESSAGE_OBJECTS += $(MESSAGE_SRCFILES:.c=.o)
MESSAGE_SHARED_OBJECTS += $(MESSAGE_SRCFILES:.c=.shared.o)
DEPS += $(MESSAGE_SRCFILES:.c=.d)
CLEANS += $(MESSAGE_OBJECTS) $(MESSAGE_SHARED_OBJECTS)

# network module
NETWORK_SRCFILES := $(wildcard $(COVERED_DIRPATH)/network/*.c)
NETWORK_OBJECTS += $(NETWORK_SRCFILES:.c=.o)
NETWORK_SHARED_OBJECTS += $(NETWORK_SRCFILES:.c=.shared.o)
DEPS += $(NETWORK_SRCFILES:.c=.d)
CLEANS += $(NETWORK_OBJECTS) $(NETWORK_SHARED_OBJECTS)

# statistics module
STATISTICS_SRCFILES := $(wildcard $(COVERED_DIRPATH)/statistics/*.c)
STATISTICS_OBJECTS += $(STATISTICS_SRCFILES:.c=.o)
STATISTICS_SHARED_OBJECTS += $(STATISTICS_SRCFILES:.c=.shared.o)
DEPS += $(STATISTICS_SRCFILES:.c=.d)
CLEANS += $(STATISTICS_OBJECTS) $(STATISTICS_SHARED_OBJECTS)

# workload module
WORKLOAD_SRCFILES := $(wildcard $(COVERED_DIRPATH)/workload/*.c) $(wildcard $(COVERED_DIRPATH)/workload/cachebench/*.c)
WORKLOAD_OBJECTS += $(WORKLOAD_SRCFILES:.c=.o)
WORKLOAD_SHARED_OBJECTS += $(WORKLOAD_SRCFILES:.c=.shared.o)
DEPS += $(WORKLOAD_SRCFILES:.c=.d)
CLEANS += $(WORKLOAD_OBJECTS) $(WORKLOAD_SHARED_OBJECTS)

COVERED_OBJECTS = $(BENCHMARK_OBJECTS) $(CACHE_OBJECTS) $(CLOUD_OBJECTS) $(COMMON_OBJECTS) $(EDGE_OBJECTS) $(MESSAGE_OBJECTS) $(NETWORK_OBJECTS) $(STATISTICS_OBJECTS) $(WORKLOAD_OBJECTS)