# rocksdb module

ROCKSDB_DIRPATH := lib/rocksdb-8.1.1

ROCKSDB_LDDIR := -L$(ROCKSDB_DIRPATH)
LDDIR += $(ROCKSDB_LDDIR)
ROCKSDB_LDLIBS := -lrocksdb
LDLIBS += $(ROCKSDB_LDLIBS)

ROCKSDB_INCDIR := -I$(ROCKSDB_DIRPATH)/include
INCDIR += $(ROCKSDB_INCDIR)