#pragma once

#include <cc_define.h>

// Siyuan: src/cache/segcache/build/segcache_config.h (NOTE: segcache_config.h is generated by CMake; use segcache_config.h instead of config.h to avoid conflicting name with libCacheSim's config.h in GLCache project)
#include <segcache_config.h>

struct addrinfo;

/* Daemonize the process (have it run in the background) */
void daemonize(void);

/* Print the current version executable */
void show_version(void);

/* Init ai */
rstatus_i getaddr(struct addrinfo **ai, char *hostname, char *servname);

/* Create pid file */
void create_pidfile(const char *filename);

/* Remove pid file */
void remove_pidfile(const char *filename);
